openapi: 3.0.0
info:
  title: MoriPo Backend API
  description: オープンソース地域通貨もりポのCloudFunctionのAPI仕様
  version: alpha
servers:
  - url: http://staging-api.example.com
    description: StaginAPI endpoint
paths:
  /point-voucher/:id:
    get:
      tags:
        - PointVoucher
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      summary: ポイント引換の詳細情報
      responses:
        '200': # status code
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  event_name:
                    type: string
                  event_description:
                    type: string
                  event_image:
                    type: string
                    example: https://image.hoge.com/vaucher/1234.jpg
                  point_amount:
                    type: number
                  max_receivable_tickets:
                    type: number
                    description: このVaucherで取得できるTicketの最大枚数
                  received_tickets:
                    type: number
                    description: このVaucherで取得したTicketの枚数
                  event_date:
                    type: number
                    example: 1677423600
                    description: イベント開催日（unix秒）
                  expired_at:
                    type: number
                    example: 1680274800
                    description: Vaucherの有効期限（unix秒）
        '404':
          description: 存在しない
    post:
      tags:
        - PointVoucher
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      summary: ポイントの取得
      responses:
        '200':
          description: ポイント取得成功
        '403':
          description: 有効期限切れ or 取得上限
  /point-tickets:
    get:
      tags:
        - 'PointTicket'
      security:
        - ApiKeyAuth: []
      summary: '所持ポイントチケットの一覧'
      responses:
        '200':
          description: 成功

    post:
      tags:
        - 'PointTicket Shop'
      security:
        - ApiKeyAuth: []
      summary: 'ポイントチケット利用'
      responses:
        '200':
          description: 成功

  /point-tickets/onetime-nonce:
    post:
      tags:
        - 'PointTicket'
      security:
        - ApiKeyAuth: []
      summary: 'ポイントチケット利用のためのワンタイムナンスの発行'
      responses:
        '200':
          description: 成功
  /shops:
    get:
      tags:
        - 'Shop'
      summary: '使える店舗一覧の取得'
      responses:
        '200':
          description: 成功
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: LINE-ID-TOKEN
