openapi: 3.0.0
info:
  title: MoriPo Backend API
  description: オープンソース地域通貨もりポのCloudFunctionのAPI仕様
  version: alpha
servers:
  - url: http://staging-api.example.com
    description: StaginAPI endpoint
paths:
  /point-voucher/:id:
    get:
      tags:
        - PointVoucher
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      summary: ポイント引換の詳細情報
      responses:
        '200': # status code
          description: 成功
    post:
      tags:
        - PointVoucher
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      summary: ポイントの取得
      responses:
        '200':
          description: ポイント取得成功
  /point-tickets:
    get:
      tags:
        - 'PointTicket'
      security:
        - ApiKeyAuth: []
      summary: '所持ポイントチケットの一覧'
      responses:
        '200':
          description: 成功
    post:
      tags:
        - 'PointTicket'
      security:
        - ApiKeyAuth: []
      summary: 'ポイントチケット利用'
      responses:
        '200':
          description: 成功
  /point-tickets/onetime-nonce:
    post:
      tags:
        - 'PointTicket'
      security:
        - ApiKeyAuth: []
      summary: 'ポイントチケット利用のためのワンタイムナンスの発行'
      responses:
        '200':
          description: 成功
  /shops:
    get:
      tags:
        - 'Shop'
      summary: '使える店舗一覧の取得'
      responses:
        '200':
          description: 成功
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: LINE-ID-TOKEN
